services:
  # Веб-сервис для основного приложения
  - type: web
    name: bnal-bank
    env: node
    plan: free
    # Настройки сборки и запуска
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    # Автоматический деплой при обновлении ветки
    autoDeploy: true
    # Постоянное хранилище для базы данных (только в платных планах)
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    # Переменные окружения
    envVars:
      - key: NODE_ENV
        value: production
      - key: WEBAPP_URL
        sync: false  # Заполнить после деплоя
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # Должен быть установлен пользователем